<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.GangOfFour\Reefact.LivingDocumentation.Attributes.GangOfFour.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.DomainDrivenDesign\Reefact.LivingDocumentation.Attributes.DomainDrivenDesign.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.EnterpriseApplicationArchitecture\Reefact.LivingDocumentation.Attributes.EnterpriseApplicationArchitecture.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.EnterpriseIntegration\Reefact.LivingDocumentation.Attributes.EnterpriseIntegration.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.AnalysisPatterns\Reefact.LivingDocumentation.Attributes.AnalysisPatterns.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.AccountingPatterns\Reefact.LivingDocumentation.Attributes.AccountingPatterns.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Idioms\Reefact.LivingDocumentation.Attributes.Idioms.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Usage.TrainOperations\Reefact.LivingDocumentation.Attributes.Usage.TrainOperations.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Usage.Invoicing\Reefact.LivingDocumentation.Attributes.Usage.Invoicing.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Usage.RailNetwork\Reefact.LivingDocumentation.Attributes.Usage.RailNetwork.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Usage.TrainOperations.Contracts\Reefact.LivingDocumentation.Attributes.Usage.TrainOperations.Contracts.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Usage.ParkingPermits\Reefact.LivingDocumentation.Attributes.Usage.ParkingPermits.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Usage.BloodBank.Domain\Reefact.LivingDocumentation.Attributes.Usage.BloodBank.Domain.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Usage.BloodBank.Application\Reefact.LivingDocumentation.Attributes.Usage.BloodBank.Application.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Usage.BloodBank.Infrastructure\Reefact.LivingDocumentation.Attributes.Usage.BloodBank.Infrastructure.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Usage.BloodBank.Ui\Reefact.LivingDocumentation.Attributes.Usage.BloodBank.Ui.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Usage.Observatory.Instruments\Reefact.LivingDocumentation.Attributes.Usage.Observatory.Instruments.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Usage.Observatory.Spectrograph\Reefact.LivingDocumentation.Attributes.Usage.Observatory.Spectrograph.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Usage.Observatory.WideFieldCamera\Reefact.LivingDocumentation.Attributes.Usage.Observatory.WideFieldCamera.csproj" />
  </ItemGroup>

</Project>
