<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <!-- Written by a different team, three years after the spectrograph, against the same core and with no
       reference to it. -->
  <ItemGroup>
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.DomainDrivenDesign\Reefact.LivingDocumentation.Attributes.DomainDrivenDesign.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Usage.Observatory.Instruments\Reefact.LivingDocumentation.Attributes.Usage.Observatory.Instruments.csproj" />
  </ItemGroup>

</Project>
