#region Usings declarations


using Reefact.LivingDocumentation.Attributes.MicroservicesPatterns;

#endregion

namespace Reefact.LivingDocumentation.Attributes.Usage.MicroservicesPatterns.ServerSidePageFragmentCompositionSample {

    // The customer account page shows a balance, a last reading and whether the street is out. Three teams
    // own those three answers, and one page has to contain them.
    //
    // SERVER-SIDE PAGE FRAGMENT COMPOSITION lets each team render its own region and assembles them on the
    // server. Each fragment ships on its own cadence; the page belongs to a team that owns no fragment, and
    // a slow fragment is a slow page.

    /// <summary>
    ///     The balance panel, generated by the billing team.
    /// </summary>
    /// <remarks>
    ///     Released on billing's cadence, into a page owned by somebody else. That is the point of the
    ///     pattern and the reason the two roles are annotated separately.
    /// </remarks>
    [ServerSidePageFragmentComposition.Fragment(PageTemplate = typeof(IAccountPageTemplate))]
    public interface IBalanceFragment {

        string RenderHtml(string supplyPoint);

    }

    /// <summary>
    ///     The outage banner, generated by the outages team.
    /// </summary>
    [ServerSidePageFragmentComposition.Fragment(PageTemplate = typeof(IAccountPageTemplate))]
    public interface IOutageBannerFragment {

        string RenderHtml(string supplyPoint);

    }

    /// <summary>
    ///     The page the fragments land in.
    /// </summary>
    /// <remarks>
    ///     Owned by a team that owns none of the fragments, and the place where a slow fragment becomes a
    ///     slow page. Naming it is how somebody finds out what a page actually depends on.
    /// </remarks>
    [ServerSidePageFragmentComposition.PageTemplate]
    public interface IAccountPageTemplate {

        string Compose(string supplyPoint);

    }
}
