<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.DomainDrivenDesign\Reefact.LivingDocumentation.Attributes.DomainDrivenDesign.csproj" />
    <ProjectReference Include="..\Reefact.LivingDocumentation.Attributes.Usage.BloodBank.Domain\Reefact.LivingDocumentation.Attributes.Usage.BloodBank.Domain.csproj" />
  </ItemGroup>

</Project>
